### PR TITLE
Implement directory removal and free space detection

### PR DESCRIPTION
**Pull request by nomeata**
This implements #1 and #3. I used #1 in production so far.

### CODE REVIEW

**Comment by dspinellis** [comment]
Thank you!  I'd love to integrate your changes.  However, it seems they are against an older version.  Can you please modify the pull request against the current version?  While at it, please also update the documentation (file `fileprune.1`).

**Comment by nomeata** [comment]
I’ll look into them. They are actually older than your commit, but I just never clicked the „Pull request“ button ;-)

**Comment by dspinellis** [comment]
I know, I tried to understand what was going on when I tried to merge them.  Anyway, if it's too difficult for you, I can give it a try. I can certainly do the documentation part, if you're not comfortable with troff.

**Comment by nomeata** [comment]
Nah, troff is not the problem. I just didn’t find the time yet to look at and understand your changes since my commits. But I have now started to use my fork in two different setups, both deleting directories based on their filename, and it seems to work fine.

**Comment by nomeata** [comment]
I have just rebased my commits. Having them merged would make it easier for me to contribute futher fixes :-)

I should say that I am not using the deletion-until-space-free feature right now, because I have several backups on that partition, so deleting snapshots from just one of them until the space is free is not fair scheduling.

**Pull request merged**
